# Generated by Django 4.2.4 on 2023-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_stems', models.PositiveIntegerField(choices=[(0, '0-20 stems'), (1, '20-50 stems'), (2, '50-100 stems')])),
                ('number_of_days', models.PositiveIntegerField(choices=[(1, '1 day'), (2, '2 days')])),
            ],
        ),
    ]
