# Generated by Django 4.2.4 on 2023-08-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='number_of_days',
            field=models.PositiveIntegerField(choices=[(1, '1-5 days'), (2, '6-10 days'), (3, '11-15 days')]),
        ),
        migrations.AlterField(
            model_name='mix',
            name='number_of_stems',
            field=models.PositiveIntegerField(choices=[(0, '0-50 stems'), (1, '50-100 stems')]),
        ),
    ]
